import type { Metadata } from "next";
import { cookies } from "next/headers";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DEFAULT_THEME, THEME_COOKIE_NAME, isTheme } from "./lib/theme";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const cookieTheme = cookieStore.get(THEME_COOKIE_NAME)?.value;
  const theme = isTheme(cookieTheme) ? cookieTheme : DEFAULT_THEME;

  return (
    <html
      lang="en"
      className={theme === "dark" ? "dark" : undefined}
      style={{ colorScheme: theme }}
    >
      <body className="antialiased min-h-screen">
        {children}
      </body>
    </html>
  );
}
